version: '3.8'
services:
  panel-supply-backend-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - panel-supply-backend-db
  panel-supply-backend-db:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - panel-supply_data:/var/lib/mysql
volumes:
  panel-supply_data:
    driver: local
