version: '3.8'
services:
  panel-supply-backend-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www/html/app
      - ./docker/php-fpm.conf:/etc/php83/php-fpm.conf
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html/public
      - ./routes:/var/www/html/routes
      - ./tests:/var/www/html/tests
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./.env:/var/www/html/.env
    depends_on:
      - panel-supply-backend-db
  panel-supply-backend-db:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - panel-supply_data:/var/lib/mysql
volumes:
  panel-supply_data:
    driver: local
